Ds:
  k3050:
    fd_syst: 0.005 # flat in pt
    fit_syst: [0.005,
               0.005,
               0.008,
               0.008,
               0.010,
               0.010,
               0.025,
               0.025,
               0.030,
               ]
    reso_syst: 0.002
  k3040:
    fd_syst: 0.005 # flat in pt
    fit_syst: [0.005,
               0.005,
               0.008,
               0.008,
               0.010,
               0.010,
               0.025,
               0.025,
               0.030,
               ]
    reso_syst: 0.002
  k4050:
    fd_syst: 0.005 # flat in pt
    fit_syst: [0.004,
               0.004,
               0.010,
               0.010,
               0.010,
               0.010,
               0.025,
               0.025,
               0.030,
               ]
    reso_syst: 0.005
  k6080:
    fd_syst: 0.005 # flat in pt
    fit_syst: [0.010,
               0.010,
               0.010,
               0.010,
               0.010,
               0.020,
               0.030
               ]
    reso_syst: 0.015

D0:
  k3050_wide_fd:
    fd_syst: 0.003 # maximum value of all the bins
    fit_syst: [
      0.07,
      0.03,
      0.02,
      0.02,
      0.02,
      0.02,
    ]
    reso_syst: 0.002
  k3050_wide_prompt:
      fd_syst: 0.0003 # maximum value of all the bins
      fit_syst: [
        0.003,
        0.001,
        0.001,
        0.001,
        0.002,
        0.004,
        0.004,
        0.005,
        0.005,
        0.005,
        0.012,
        0.02,
      ]
      reso_syst: 0.002
  k3050:
    fd_syst: 0.002 # maximum value of all the bins
    fit_syst: [
      0.002,
      0.002,
      0.002,
      0.002,
      0.002,
      0.002,
    ]
    reso_syst: 0.015
  k3040:
    fd_syst: 0.0002 # maximum value of all the bins
    fit_syst: [
      0.007,
      0.002,
      0.002,
      0.001,
      0.001,
      0.001,
      0.001,
      0.002,
      0.002,
      0.002,
      0.002,
      0.005,
      0.009,
      0.012,
      0.025,
    ]
    reso_syst: 0.002
  k4050:
    fd_syst: 0.0003 # maximum value of all the bins
    fit_syst: [
      0.005,
      0.003,
      0.002,
      0.001,
      0.001,
      0.001,
      0.001,
      0.002,
      0.004,
      0.004,
      0.005,
      0.005,
      0.005,
      0.015,
      0.015,
    ]
    reso_syst: 0.005
  k6080:
    fd_syst: 0.0002 # maximum value of all the bins
    fit_syst: [
      0.002,
      0.001,
      0.001,
      0.004,
      0.004,
      0.006,
      0.006,
      0.018
    ]
    reso_syst: 0.015
  
Dplus:
  k3040:
    fd_syst: 0.002 # maximum value of all the bins
    fit_syst: [
      0.005,
      0.004,
      0.004,
      0.005,
      0.005,
      0.005,
      0.005,
      0.005,
      0.010,
      0.010,
      0.010,
      0.010,
      0.010,
      0.010,
    ]
    reso_syst: 0.002
  k3050:
    fd_syst: 0.002 # maximum value of all the bins
    fit_syst: [
      0.005,
      0.004,
      0.004,
      0.005,
      0.005,
      0.005,
      0.005,
      0.005,
      0.010,
      0.010,
      0.010,
      0.010,
      0.010,
      0.010,
    ]
    reso_syst: 0.002
  k4050:
    fd_syst: 0.002 # maximum value of all the bins
    fit_syst: [
      0.010,
      0.005,
      0.005,
      0.005,
      0.005,
      0.010,
      0.010,
      0.010,
      0.010,
      0.010,
      0.010,
      0.010,
      0.010,
      0.020
    ]
    reso_syst: 0.005
  k6080:
    fd_syst: 0.002 # maximum value of all the bins
    fit_syst: [
      0.040,
      0.010,
      0.006,
      0.006,
      0.008,
      0.010,
      0.010,
      0.010,
      0.020,
    ]
    reso_syst: 0.015
