plot_invmass_fit: true
plot_charm: true
plot_lf: true
zipfiles: true

# input files and objects
input:
  Dzero:
    fitfile: '/home/spolitan/alice/hf-vn/cutvar_D0_combined/raw_yields/raw_yields_00.root'
    v2file: '/home/spolitan/alice/hf-vn/syst/v2_wsyst/v2_prompt_wsyst_D0_barlow.root'
    graph: 'gvn_prompt_stat'
    syst: 'tot_syst'
  Dplus:
    fitfile: '/home/spolitan/alice/hf-vn/raw_yields_00_dplus.root'
    v2file: '/home/spolitan/alice/hf-vn/syst/v2_wsyst/v2_prompt_wsyst_Dp_barlow.root'
    graph: 'gvn_prompt_stat'
    syst: 'tot_syst'
  Ds:
    fitfile: '/home/spolitan/alice/ds_v2_oo/output/181225/cutvar_20_combined/raw_yields/raw_yields_00.root'
    v2file: '/home/spolitan/alice/hf-vn/syst/v2_wsyst/v2_prompt_wsyst_evsel.root'
    graph: 'gvn_prompt_stat'
    syst: 'tot_syst'
  Lambda:
    v2file: '/home/spolitan/alice/alice-correlation/figures/lf_v2_vscent_systfrombase.root'
    graph: 'gist_lambda_010'
    syst: 'syst_lambda_010'
  K0:
    v2file: '/home/spolitan/alice/alice-correlation/figures/lf_v2_vscent_systfrombase.root'
    graph: 'gist_k0_010'
    syst: 'syst_k0_010'
  Phi:
    v2file: false #'/home/spolitan/alice/alice-correlation/figures/lf_v2_vscent_systfrombase.root'
    graph: 'gist_phi_010'
    syst: 'syst_phi_010'
  Katz:
    v2file: '/home/spolitan/alice/hf-vn/figures/models/oo_v2_D0_katz.txt'
  Langevin:
    v2file: '/home/spolitan/alice/hf-vn/figures/models/oo_v2_D0_langevin.txt'
  Epos4HQ:
    v2file: '/home/spolitan/alice/hf-vn/figures/models/oo_v2_D0_epos4hq.txt'

# simfit style
simfit_style:
  Dzero:
    ptindex: 5
    ptmin: 3.0
    ptmax: 3.5
    hasfeflections: true
    massmin: 1.74
    massmax: 1.98
    ymin_mass: 10
    ymax_mass: 85000
    ymin_v2: 0.0
    ymax_v2: 0.285
    axisnamebottom: ';#it{M}(K#pi) (GeV/#it{c}^{2});#it{v}_{2}^{obs.}{SP, |#Delta#it{#eta}|>1.3}'
    latex:
      pad1:
        - [0.25, 0.84, 'ALICE Preliminary', 0.07]
        - [0.25, 0.76, 'OO, FT0C 0#minus20%, #sqrt{#it{s}_{NN}} = 5.36 TeV', 0.058]
        - [0.25, 0.68, 'D^{0} #rightarrow K^{#font[122]{-}}#pi^{+} and charge conj.', 0.058]
        - [0.25, 0.60, '3.0 < #it{p}_{T} < 3.5 GeV/#it{c}', 0.058]
      pad2:
        - [0.25, 0.92, '#it{v}_{2}^{obs.} = 0.095 #pm 0.008', 0.058]
  Dplus:
    ptindex: 3
    ptmin: 3.0
    ptmax: 3.5
    massmin: 1.751
    massmax: 1.97
    ymin_mass: -1200
    ymax_mass: 35000
    ymin_v2: 0.0
    ymax_v2: 0.285
    axisnamebottom: ';#it{M}(K#pi#pi) (GeV/#it{c}^{2});#it{v}_{2}^{obs.}{SP, |#Delta#it{#eta}|>1.3}'
    latex:
      pad1:
        - [0.25, 0.84, 'ALICE Preliminary', 0.07]
        - [0.25, 0.76, 'OO, FT0C 0#minus20%, #sqrt{#it{s}_{NN}} = 5.36 TeV', 0.058]
        - [0.25, 0.68, 'D^{+} #rightarrow K^{-}#pi^{+}#pi^{+} and charge conj.', 0.058]
        - [0.25, 0.60, '3.0 < #it{p}_{T} < 3.5 GeV/#it{c}', 0.058]
      pad2:
        - [0.25, 0.92, '#it{v}_{2}^{obs.} = 0.110 #pm 0.013', 0.058]
  Ds:
    ptindex: 1
    ptmin: 2.0
    ptmax: 3.0
    massmin: 1.78
    massmax: 2.04
    ymin_mass: 10
    ymax_mass: 8800
    ymin_v2: 0.0
    ymax_v2: 0.325
    axisnamebottom: ';#it{M}(KK#pi) (GeV/#it{c}^{2});#it{v}_{2}^{obs.}{SP, |#Delta#it{#eta}|>1.3}'
    latex:
      pad1:
        - [0.25, 0.84, 'ALICE Preliminary', 0.07]
        - [0.25, 0.76, 'OO, FT0C 0#minus20%, #sqrt{#it{s}_{NN}} = 5.36 TeV', 0.058]
        - [0.25, 0.68, 'D_{s}^{+} #rightarrow #phi#pi^{+} #rightarrow K^{-}K^{+}#pi^{+} and charge conj.', 0.058]
        - [0.25, 0.60, '2.0 < #it{p}_{T} < 3.0 GeV/#it{c}', 0.058]
      pad2:
        - [0.25, 0.92, '#it{v}_{2}^{obs.} = 0.096 #pm 0.044', 0.058]

# style for final charm v2 plot
charm_v2_style:
  axisname: ";#it{p}_{T} (GeV/#it{c}); #it{v}_{2}{SP, |#Delta#it{#eta}| > 1.3}"
  ymin: -0.04
  ymax: 0.30
  xmin: -0.5
  xmax: 8.5
  setlogx: false
  latex:
    - [0.20, 0.86, 'ALICE Preliminary', 0.06]
    - [0.20, 0.81, 'OO #sqrt{#it{s}_{NN}} = 5.36 TeV, FT0C 0#minus20%', 0.04]

# style for final light-flavor v2 plot
lf_v2_style:
  axisname: ";#it{p}_{T} (GeV/#it{c}); #it{v}_{2}"
  ymin: -0.04
  ymax: 0.35
  xmin: -0.5
  xmax: 8.5
  setlogx: false
  latex:
    - [0.20, 0.86, 'ALICE Preliminary', 0.06]
    - [0.20, 0.81, 'OO #sqrt{#it{s}_{NN}} = 5.36 TeV', 0.04]
  leg_hf:
    header: 'SP, FT0C 0#minus20%, |#Delta#it{#eta}| > 1.3'
    xmax: 0.4
    ncolumns: 1
    ymin: 0.54
    textsize: 0.033
    xmin: 0.196
    ymax: 0.68
  leg_lf:
    header: '2PC, FT0C 0#minus10%, 1.2 < |#Delta#it{#eta}| < 1.8'
    xmax: 0.6
    ncolumns: 2
    ymin: 0.68
    textsize: 0.033
    xmin: 0.196
    ymax: 0.78

# global style
style:
  Dplus:
    color: 'kOrange+7'
    marker: 'kFullSquare'
    markersize: 1.2
    alpha: 0.8
  Dzero:
    color: 'kRed+1'
    marker: 'kFullCircle'
    markersize: 1.2
    alpha: 0.8
  Ds:
    color: 'kAzure+4'
    marker: 'kFullDiamond'
    markersize: 1.8
    alpha: 0.7
  Lambda:
    color: 'kTeal-6'
    marker: 'kFullCross'
    markersize: 1.4
    alpha: 0.8
  K0:
    color: 'kOrange+7'
    marker: 'kFullSquare'
    markersize: 1.2
    alpha: 0.8
  Phi:
    color: 'kOrange+7'
    marker: 'kFullDiamond'
    markersize: 1.4
    alpha: 0.8
  Katz:
    color: 'kBlack'
    linestyle: 2
    linewidth: 4
    alpha: 0.7
  Langevin:
    color: 'kAzure+4'
    alpha: 0.7
    linestyle: 3
    linewidth: 6
  Epos4HQ:
    color: 'kTeal-6'
    alpha: 0.7
    linestyle: 7
    linewidth: 4


# output
outdir: './preliminary_sqm26/'
suffix: 'oo_v2_preliminary_v0'
output_formats: ['pdf']
