operations:
    preprocess_data: false
    preprocess_mc: false
    make_yaml: false
    proj_data: false
    proj_mc: false
    efficiencies: true
    get_vn_vs_mass: false

outdir: '/home/mdicosta/alice/hf-vn/test_output'
suffix: 'test'
centrality: 'k3050'
Dmeson: 'Dplus'
nworkers: 1

# pt bins
ptbins: [
           1.0,
           1.5,
           2.0,
           2.5,
           3.0,
           3.5,
           4.0,
           5.0,
           6.0,
           7.0,
           8.0,
           10.0,
           12.0,
           16.0,
           24.0
       ]

# cut variation
cut_variation:
    corr_bdt_cut:
        bkg_max: [0.004, 0.004, 0.015, 0.015, 0.02, 0.02, 0.015, 0.015, 0.007, 0.01, 0.006, 0.006, 0.02, 0.02]
        sig: # the max value is not contained in the range
            min: [0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.04, 0.04]
            max: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.60, 0.60]
            step: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    uncorr_bdt_cut:
        bkg_max: # max probability for bkg, one for each pt bin
            - [0.01, 0.02, 0.008, 0.002] # pt 1
            - [0.04, 0.02, 0.02, 0.002] # pt 2
            - [0.03, 0.03, 0.01, 0.006, 0.002] # pt 3
            - [0.06, 0.06, 0.01, 0.006, 0.004] # pt 4
            - [0.06, 0.06, 0.03, 0.01, 0.004] # pt 5
            - [0.1, 0.07, 0.03, 0.004, 0.006] # pt 6
            - [0.03, 0.01, 0.006, 0.006, 0.004] # pt 7
            - [0.03, 0.1, 0.04, 0.01, 0.004] # pt 8
            - [0.02, 0.02, 0.02, 0.006, 0.002] # pt 9
            - [0.024, 0.024, 0.024, 0.004, 0.002] # pt 10
            - [0.006, 0.006, 0.002, 0.002] # pt 11
            - [0.006, 0.006, 0.002, 0.002] # pt 12
            - [0.15, 0.15, 0.15, 0.05] # pt 13
            - [0.09, 0.06, 0.06] # pt 14
        sig:
            - [0.00, 0.40, 0.70, 0.90, 1.00] # pt 1
            - [0.00, 0.50, 0.70, 0.90, 1.00] # pt 2
            - [0.00, 0.20, 0.45, 0.75, 0.90, 1.00] # pt 3
            - [0.00, 0.30, 0.50, 0.75, 0.90, 1.00] # pt 4
            - [0.00, 0.30, 0.50, 0.70, 0.85, 1.00] # pt 5
            - [0.00, 0.25, 0.40, 0.70, 0.90, 1.00] # pt 6
            - [0.00, 0.25, 0.45, 0.65, 0.85, 1.00] # pt 7
            - [0.00, 0.25, 0.45, 0.65, 0.85, 1.00] # pt 8
            - [0.00, 0.25, 0.45, 0.65, 0.85, 1.00] # pt 9
            - [0.00, 0.25, 0.45, 0.65, 0.85, 1.00] # pt 10
            - [0.00, 0.30, 0.50, 0.75, 1.00] # pt 11
            - [0.00, 0.40, 0.60, 0.75, 1.00] # pt 12
            - [0.00, 0.40, 0.60, 0.75, 1.00] # pt 13
            - [0.00, 0.50, 0.70, 1.00] # pt 14


projections:
    # PtWeightsFile: '/home/mdicosta/alice/hf-vn/ptweights/weights/Dplus/k3050/pTweight_Dplus_k3050_test_Dplus.root'
    ApplyPtWeightsD: False
    ApplyPtWeightsB: False
    ApplyBSpeciesWeights: False
    storeML: False
    inv_mass_bins: [
                    [1.70,1.72,1.73,1.74,1.75,1.78,1.81,1.83,1.85,1.87,1.89,1.92,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.78,1.81,1.83,1.85,1.87,1.89,1.92,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.65,1.66,1.67,1.68,1.69,1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.65,1.69,1.73,1.77,1.81,1.83,1.85,1.87,1.89,1.91,1.93,1.97,2.01,2.05],
                    [1.65,1.69,1.73,1.77,1.81,1.83,1.85,1.87,1.89,1.91,1.93,1.97,2.01,2.05,2.09,2.13,2.17],
                    [1.65,1.69,1.73,1.77,1.81,1.83,1.85,1.87,1.89,1.91,1.93,1.97,2.01,2.05,2.09,2.13,2.17],
                    ]

preprocess:
    data:
        '2023':
            files: [
                  /data/mdicosta/DplusFlow/3050/MERGED_0.root,
                  /data/mdicosta/DplusFlow/3050/MERGED_1.root,
                  /data/mdicosta/DplusFlow/3050/MERGED_2.root,
                  /data/mdicosta/DplusFlow/3050/MERGED_3.root,
                  /data/mdicosta/DplusFlow/3050/MERGED_4.root,
                  /data/mdicosta/DplusFlow/3050/MERGED_5.root,
                  /data/mdicosta/DplusFlow/3050/MERGED_6.root,
                  /data/mdicosta/DplusFlow/3050/MERGED_7.root,
                  /data/mdicosta/DplusFlow/3050/MERGED_8.root,
                  /data/mdicosta/DplusFlow/3050/MERGED_9.root,
                  /data/mdicosta/DplusFlow/3050/MERGED_10.root,
                # /home/mdicosta/alice/hf-vn/datasets/Data_Dplus_3050.root
            ]
            resolution: '/home/mdicosta/alice/hf-vn/datasets/resosp3050l_PASS4_full_PbPb_Reso.root'
        # Possibility to add more datasets, each with its resolution
        # '2024':
        #     files: [
        #         /home/mdicosta/alice/hf-vn/datasets/Data_Dplus_3050.root
        #     ]
        #     resolution: '/home/mdicosta/alice/hf-vn/datasets/resosp3050l_PASS4_full_PbPb_Reso.root'
    mc: '/home/mdicosta/alice/hf-vn/datasets/MC_Dplus_3050_vsphi_ptsmear20.root'
    axes_data: {
        "Mass": 2,      # "axis_name": rebin_factor
        "sp": 1,
        "score_bkg": 1, 
        "score_FD": 1
    }
    axes_reco: {
        "Mass": 1,
        "Pt": 1,
        "score_bkg": 1,
        "score_FD": 1
    }
    axes_gen: {
        "Pt": 1,
        "cent": 1
    }
    workers: 1
    bkg_cuts: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]

simfit:
    Sigma: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02]
    MassFitRanges: [
        [1.75, 2.05],
        [1.75, 2.05],
        [1.75, 2.05],
        [1.75, 2.05],
        [1.75, 2.05],
        [1.75, 2.05],
        [1.75, 2.05],
        [1.75, 2.05],
        [1.70, 2.05],
        [1.70, 2.05],
        [1.66, 1.97],
        [1.66, 2.04],
        [1.66, 2.17],
        [1.66, 2.17],
           ]
    BkgFunc: 'kExpo' # background function. If a single value is provided, it will be used for all pt bins.
    SgnFunc: 'kGaus' # signal function. If a single value is provided, it will be used for all pt bins.
    BkgFuncVn: 'kLin' # background function for vn. If a single value is provided, it will be used for all pt bins.
    
    #_________________________________________________________________________________________________________________________
    # Optional fit configurations, if not set, the default values will be used. If single value is provided, it will be used for all pt bins.
    #FixMean: 0 # 0: do not fix mean, 1: fix mean, default: 0
    #MeanFile: '' # default: ''
    #BoundMean: 0 # 0: Do not set limits on mean range, 1: the mean is set to be between MassMin[i] and MassMax[i]
    #FixSigma: 0 # default: 0
    #FixSigmaFromFile: '' # default: ''
    #SigmaFile: '' # default: ''
    #SigmaMultFactor: 1. # default: 1
    #FixSigmaRatio: 0 # default: 0
    #SigmaRatioFile: "" # default: ""
    #NSigma4SB: 3 # optional
    #Rebin: 1 # optional, default: 1
    #InclSecPeak: 0 # 0: do not include secondary peak, 1: include secondary peak, default: 0
    #SigmaSecPeak: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02] # optional, default: []. If InclSecPeak = 1, then SigmaSecPeak must be provided.
    #SigmaFileSecPeak: '' # optional, default: ''
    #SigmaMultFactorSecPeak: 1. # optional, default: 1
    #FixSigmaToFirstPeak: 0 # 0: do not fix sigma to the first peak, 1: fix sigma to the first peak, default: 0
    #enableRef: false #reflection for D0. 
    #ReflFunc: "2gaus" # reflection function, default: "2gaus". D0 specific, not available for others
    #reflFile: ''
    # if `enableRef` is set to `true`,  and `ReflFile` is empty, then `ReflFile` will be aotumatically filled.
    # if `ReflFile` is filled, then it will use the filled one
    #__________________________________________________________________________________________________________________________
