operations:
    preprocess: true
    make_yaml: true
    proj_data: true
    proj_mc: true
    efficiencies: true
    get_vn_vs_mass: true
    do_cut_variation: false
    data_driven_fraction: false
    get_v2_vs_frac: false

outdir: '/home/mdicosta/alice/hf-vn/test_output'
# outdirPrep: '/home/wuct/ALICE/local/dev/d0_v2'
suffix: 'test'
centrality: 'k3050'
Dmeson: 'Dplus'

# pt bins
ptbins: [
        #    1.0,
        #    1.5,
        #    2.0,
           2.5,
           3.0,
        #    3.5,
        #    4.0,
        #    5.0,
        #    6.0,
        #    7.0,
        #    8.0,
        #    10.0,
        #    12.0,
        #    16.0,
        #    24.0
       ]

# cut variation
cut_variation:
    corr_bdt_cut:
        bkg_max: [0.004, 0.004, 0.015, 0.015, 0.02, 0.02, 0.015, 0.015, 0.007, 0.01, 0.006, 0.006, 0.02, 0.02]
        sig: # the max value is not contained in the range
            min: [0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.04, 0.04]
            max: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.60, 0.60]
            step: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        skip_cuts: [    # index of the specific cuts to skip for each pt bin
                [18,19,20,21,22,23,24,25], # pt 1
                [26], # pt 2
                [24,25,26], # pt 3
                [], # pt 4
                [], # pt 5
                [], # pt 6
                [], # pt 7
                [], # pt 8
                [], # pt 9
                [22,23,24,25,26], # pt 10
                [22,23,24,25,26], # pt 11
                [22,23,24,25,26], # pt 12
                [21,22,23,24,25,26], # pt 13
                [21,22,23,24,25,26], # pt 14
                [5,9], # pt 15
            ]
    uncorr_bdt_cut:
        bkg_max: # max probability for bkg, one for each pt bin
            - [0.01, 0.02, 0.008, 0.002] # pt 1
            - [0.04, 0.02, 0.02, 0.002] # pt 2
            - [0.03, 0.03, 0.01, 0.006, 0.002] # pt 3
            - [0.06, 0.06, 0.01, 0.006, 0.004] # pt 4
            - [0.06, 0.06, 0.03, 0.01, 0.004] # pt 5
            - [0.1, 0.07, 0.03, 0.004, 0.006] # pt 6
            - [0.03, 0.01, 0.006, 0.006, 0.004] # pt 7
            - [0.03, 0.1, 0.04, 0.01, 0.004] # pt 8
            - [0.02, 0.02, 0.02, 0.006, 0.002] # pt 9
            - [0.024, 0.024, 0.024, 0.004, 0.002] # pt 10
            - [0.006, 0.006, 0.002, 0.002] # pt 11
            - [0.006, 0.006, 0.002, 0.002] # pt 12
            - [0.15, 0.15, 0.15, 0.05] # pt 13
            - [0.09, 0.06, 0.06] # pt 14
        sig:
            - [0.00, 0.40, 0.70, 0.90, 1.00] # pt 1
            - [0.00, 0.50, 0.70, 0.90, 1.00] # pt 2
            - [0.00, 0.20, 0.45, 0.75, 0.90, 1.00] # pt 3
            - [0.00, 0.30, 0.50, 0.75, 0.90, 1.00] # pt 4
            - [0.00, 0.30, 0.50, 0.70, 0.85, 1.00] # pt 5
            - [0.00, 0.25, 0.40, 0.70, 0.90, 1.00] # pt 6
            - [0.00, 0.25, 0.45, 0.65, 0.85, 1.00] # pt 7
            - [0.00, 0.25, 0.45, 0.65, 0.85, 1.00] # pt 8
            - [0.00, 0.25, 0.45, 0.65, 0.85, 1.00] # pt 9
            - [0.00, 0.25, 0.45, 0.65, 0.85, 1.00] # pt 10
            - [0.00, 0.30, 0.50, 0.75, 1.00] # pt 11
            - [0.00, 0.40, 0.60, 0.75, 1.00] # pt 12
            - [0.00, 0.40, 0.60, 0.75, 1.00] # pt 13
            - [0.00, 0.50, 0.70, 1.00] # pt 14

minimisation:
    skip_cuts: [
        [],
        [],
        [1, 3, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53],
        [1], #, 30, 31, 32, 33, 34, 35],
        [45, 46, 47, 48, 49, 50, 51, 52, 53], #[37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53],
        [1, 2, 3, 4, 45, 46, 47, 48, 49, 50, 51, 52, 53],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57], # [33, 35, 37, 39, 41, 43, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57]
    ]
    apply_suggested_skips: True
    systematics: ['even', 'random', 'odd', 'minus3low', '1in3', '1in4', 'minus3high', 'minus3']


ptWeights:
    Bspecie: Ball # Ball or BsBmix, if empty no B pt weights
    Rebin: 1
    Smooth: 100
    PtShapeFONLL_D: /home/mdicosta/FlowDplus/MLanalysis/PtWeights/fonll_pythia_beautyFFee_charmhadrons_5dot5tev_y0dot5.root
    RaaTAMU_D: /home/mdicosta/alice/DmesonAnalysis/models/tamu/PromptD0_TAMU_RAA_5TeV_3050.txt
    PtShapeFONLL_B: /home/mdicosta/FlowDplus/MLanalysis/PtWeights/fonll_pythia_beautyFFee_charmhadrons_5dot5tev_y0dot5.root
    RaaTAMU_B: /home/mdicosta/alice/DmesonAnalysis/models/tamu/B_TAMU_RAA_5TeV_3050.txt

pt_center:
    downsample_fracs: [
        1.0,
        1.0,
        1.0,
        1.0,
        0.5,
        0.5,
        0.5,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0
    ]

projections:
    # PtWeightsFile: '/home/mdicosta/alice/hf-vn/ptweights/weights/Dplus/k3050/pTweight_Dplus_k3050_test_Dplus.root'
    ApplyPtWeightsD: False
    ApplyPtWeightsB: False
    ApplyBSpeciesWeights: False
    Resolution: '/home/mdicosta/alice/hf-vn/datasets/resosp3050l_PASS4_full_PbPb_Reso.root'
    storeML: False
    inv_mass_bins: [
                    [1.70,1.72,1.73,1.74,1.75,1.78,1.81,1.83,1.85,1.87,1.89,1.92,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.78,1.81,1.83,1.85,1.87,1.89,1.92,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.65,1.66,1.67,1.68,1.69,1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                    [1.65,1.69,1.73,1.77,1.81,1.83,1.85,1.87,1.89,1.91,1.93,1.97,2.01,2.05],
                    [1.65,1.69,1.73,1.77,1.81,1.83,1.85,1.87,1.89,1.91,1.93,1.97,2.01,2.05,2.09,2.13,2.17],
                    [1.65,1.69,1.73,1.77,1.81,1.83,1.85,1.87,1.89,1.91,1.93,1.97,2.01,2.05,2.09,2.13,2.17],
                    ]

preprocess:
    bkg_cuts: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    inputs:
    -   files: [
          "/data/mdicosta/DplusFlow/3050/Train558625/merged_runs/AnalysisResults/AnalysisResults_544028.root",
        ]
        outdir: 'FlowSP'
        sparses:
        -   name: 'FlowSP'
            path: 'hf-task-flow-charm-hadrons/hSparseFlowCharm'
            axes: {
              names: ['Mass', 'Pt', 'Cent', 'Sp', 'ScoreBkg', 'ScoreFD'],
              rebin: [1, 1, 1, 1, 1, 1]
            }
    -   files: [
          "/data/mdicosta/DplusFlow/eff/MC/Train559859/AnalysisResults_LHC25a5_allruns.root",
        ]
        outdir: 'MC'
        sparses:
        -   name: 'RecoPrompt'
            path: 'hf-task-dplus/hSparseMassPrompt'
            axes: {
              names: ['Mass', 'Pt', 'Cent', 'ScoreBkg', 'ScoreFD'],
              rebin: [1, 1, 1, 1, 1]
            }
        -   name: 'RecoFD'
            path: 'hf-task-dplus/hSparseMassFD'
            axes: {
              names: ['Mass', 'Pt', 'Cent', 'ScoreBkg', 'ScoreFD'],
              rebin: [1, 1, 1, 1, 1]
            }
        -   name: 'GenPrompt'
            path: 'hf-task-dplus/hSparseMassGenPrompt'
            axes: {
              names: ['Pt', 'Cent'],
              rebin: [1, 1]
            }
        -   name: 'GenFD'
            path: 'hf-task-dplus/hSparseMassGenFD'
            axes: {
              names: ['Pt', 'Cent'],
              rebin: [1, 1]
            }
    -   files: [
            /home/mdicosta/DFlowOO/Correlations/020_SE/oldalljobs/001/AnalysisResults_001.root,
            # /path/to/anres/for/SE/AnalysisResults.root,
        ]
        outdir: 'DataSE'
        sparses:
        -   name: 'CorrelMaps'
            path: 'hf-correlator-flow-charm-hadrons-reduced/hSparseCorrelationsSECharmHad'
            axes: {
                names: ['PoolBin', 'PtTrig', 'PtAssoc', 'DeltaEta', 'DeltaPhi', 'Mass'],
                rebin: [1, 1, 1, 1, 1, 1]
            }
        -   name: 'CorrelTrig'
            path: 'hf-correlator-flow-charm-hadrons-reduced/hSparseTrigCandsCharm'
            axes: {
                names: ['Mass', 'PtTrig', 'ScoreBkg', 'ScoreFD'],
                rebin: [1, 1, 1, 1]
            }
    -   files: [
            /home/mdicosta/DFlowOO/Correlations/1920_ME/AnalysisResults.root
            # /path/to/anres/for/ME/AnalysisResults.root,
        ]
        outdir: 'DataME'
        sparses:
        -   name: 'CorrelMaps'
            path: 'hf-correlator-flow-charm-hadrons-reduced/hSparseCorrelationsMECharmHad'
            axes: {
                names: ['PoolBin', 'PtTrig', 'PtAssoc', 'DeltaEta', 'DeltaPhi', 'Mass', 'ScoreBkg', 'ScoreFD'],
                rebin: [1, 1, 1, 1, 1, 1, 1, 1]
            }

v2extraction:
    Sigma: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02]
    MassFitRanges: [
        [1.75, 2.05],
        [1.75, 2.05],
        [1.75, 2.05],
        [1.75, 2.05],
        [1.75, 2.05],
        [1.75, 2.05],
        [1.75, 2.05],
        [1.75, 2.05],
        [1.70, 2.05],
        [1.70, 2.05],
        [1.66, 1.97],
        [1.66, 2.04],
        [1.66, 2.17],
        [1.66, 2.17],
    ]
    BkgFunc: 'kExpo' # background function. If a single value is provided, it will be used for all pt bins.
    SgnFunc: 'kGaus' # signal function. If a single value is provided, it will be used for all pt bins.
    BkgFuncVn: 'kLin' # background function for vn. If a single value is provided, it will be used for all pt bins.
    
    #_________________________________________________________________________________________________________________________
    # Optional fit configurations, if not set, the default values will be used. If single value is provided, it will be used for all pt bins.
    #FixMean: 0 # 0: do not fix mean, 1: fix mean, default: 0
    #MeanFile: '' # default: ''
    #BoundMean: 0 # 0: Do not set limits on mean range, 1: the mean is set to be between MassMin[i] and MassMax[i]
    #FixSigma: 0 # default: 0
    #FixSigmaFromFile: '' # default: ''
    #SigmaFile: '' # default: ''
    #SigmaMultFactor: 1. # default: 1
    #FixSigmaRatio: 0 # default: 0
    #SigmaRatioFile: "" # default: ""
    #NSigma4SB: 3 # optional
    #Rebin: 1 # optional, default: 1
    #InclSecPeak: 0 # 0: do not include secondary peak, 1: include secondary peak, default: 0
    #SigmaSecPeak: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02] # optional, default: []. If InclSecPeak = 1, then SigmaSecPeak must be provided.
    #SigmaFileSecPeak: '' # optional, default: ''
    #SigmaMultFactorSecPeak: 1. # optional, default: 1
    #FixSigmaToFirstPeak: 0 # 0: do not fix sigma to the first peak, 1: fix sigma to the first peak, default: 0
    #enableRef: false #reflection for D0. 
    #ReflFunc: "2gaus" # reflection function, default: "2gaus". D0 specific, not available for others
    #reflFile: ''
    # if `enableRef` is set to `true`,  and `ReflFile` is empty, then `ReflFile` will be aotumatically filled.
    # if `ReflFile` is filled, then it will use the filled one
    #__________________________________________________________________________________________________________________________

# minmissation settings
minimisation:
    #skip_cuts: [    # index of the specific cuts to skip for each pt bin in case of broken cuts
    #            [], # pt 1
    #            [], # pt 2
    #            [], # pt 3
    #            [], # pt 4
    #            [], # pt 5
    #            [], # pt 6
    #]
    #systematics: ['even', 'random', 'odd', 'minus3low', '1in3', '1in4', 'minus3high', 'minus3']