#python3 src/compute_prompt_v2_unfold.py configs/v2_prompt_v2_method_check.yml

mode:
  method: ratio   # "ratio" or "fixedFD"  1. ratio is run2's method  fixedFD: take the exact FD v2 from paper

input:
  fractions:
    file: /home/wuct/MetaData/DATA/OO/apass2/corr/results/prompt/cutvar_test_correlated/frac/frac_00.root
    # file: /home/wuct/MetaData/DATA/OO/apass2/corr/results/prompt/K2050/cutvar_test_correlated/frac/frac_00.root
    # used only when method=ratio, note: use corrected fraction here since the prompt v2 is not corrected
    objects_ratio:
      f_prompt: hPromptFracCorr
      f_FD: hFDFracCorr

    # used only when method=fixedFD
    objects_fixedFD:
      f_prompt: hPromptFrac
      f_FD: hFDFrac

  v2obs:
    file: /home/wuct/MetaData/DATA/OO/apass2/corr/results/fifth/k020_gausPer/k60100_loose2to2d5_d20/sys/central/CorrelExtract_0d2_1d3/final_results.root
    # file: /home/wuct/MetaData/DATA/OO/apass2/corr/results/fifth/k2050_wider_loose1_rebin/CorrelExtract_0d2_1d3_AppDeltaPhi/results_k2050_rebin_loose_k60100_GausPeriodic_fixed_noBL/final_results.root
    object: hv2Delta_PtBinAssoc1_InvMassBin1

assumption:
  # for ratio
  r: 0.5

  # for fixedFD
  v2_FD_fixed: 0.0248
  v2_FD_fixed_err: 0.0

output:
  file: /home/wuct/MetaData/DATA/OO/apass2/corr/results/fifth/k020_gausPer/k60100_loose2to2d5_d20/sys/results/v2_prompt_ratio_0d2_1d3.root
  object: gV2Prompt
  title: "v2^{prompt}"

checks:
  check_npoints: true
  check_fraction_sum: true
  fraction_sum_tolerance: 0.05
  min_f_prompt: 1.0e-6
