# CodeName: "010_negDeta"
# _CodeName: "Name to identify the analysis: pass7_Full_ptAssoc0p3, Thin2023_Full_ptAssoc0p3"

Dmeson: Dzero
suffix: "0d8_1d5"
outdir: "/home/wuct/MetaData/DATA/OO/apass2/corr/results/fthlook_Biao/large/k020"
pathFileSE: "/home/wuct/MetaData/DATA/OO/apass2/corr/results/fthlook_Biao/large/SE/k020/AnalysisResults_oriBDT_fulldeltaEta.root"
pathFileME: "/home/wuct/MetaData/DATA/OO/apass2/corr/results/fthlook_Biao/large/ME/k020/AnalysisResults_03.root"
pathFileMass: "/home/wuct/MetaData/DATA/OO/apass2/corr/results/fthlook_Biao/large/SE/k020/AnalysisResults_oriBDT_fulldeltaEta.root"
method: "DeltaPhiBinning" # "MassBinning" or "DeltaPhiBinning"
nWorkers: 18

task_LM:
  do: false
  suffix: "0d8_1d5"
  outdir: "/home/wuct/MetaData/DATA/OO/apass2/corr/results/fthlook_Biao/large/k60100"
  pathFileSE: "/home/wuct/MetaData/DATA/OO/apass2/corr/results/fthlook_Biao/large/SE/k60100/AnalysisResults_oriBDT_fulldeltaEta.root"
  pathFileME: "/home/wuct/MetaData/DATA/OO/apass2/corr/results/fthlook_Biao/large/ME/k80100/AnalysisResults_oriBDT_fulldeltaEta.root"
  pathFileMass: "/home/wuct/MetaData/DATA/OO/apass2/corr/results/fthlook_Biao/large/SE/k60100/AnalysisResults_oriBDT_fulldeltaEta.root"
  nDeltaPhiBins: 16

nDeltaPhiBins: 32
deltaEtaBins: [
  [-1.5, -0.8],
  [0.8, 1.5]
]
nPools: 10
doPoolByPool: false

ptBinsCand: [
            0, 
            1.0,
            1.5,
           2.0,
           2.5,
           3.0
           ]
ptBinsHad: [0.4,3]
invMassBins: [
                [1.72,1.76,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.98,2.02], # pt 1
                [1.72,1.76,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.98,2.02], # pt 2
                [1.72,1.76,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.98,2.02], # pt 3
                [1.72,1.76,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.98,2.02], # pt 4
                [1.72,1.76,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.98,2.02], # pt 5
                [1.72,1.76,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.98,2.02], # pt 6
                [1.72,1.76,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.98,2.02], # pt 7
                [1.72,1.76,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.98,2.02], # pt 8
                [1.72,1.76,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.98,2.02], # pt 8
                [1.72,1.76,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.98,2.02],
                [1.72,1.76,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.98,2.02],
                [1.72,1.76,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.98,2.02],
                [1.72,1.76,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.98,2.02],
                [1.72,1.76,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.98,2.02]
                # [1.72,1.76,1.78,1.80,1.82,1.84,1.86,1.88,1.90,1.92,1.94,1.96,1.98,2.02], # pt 1
                # [1.72,1.76,1.78,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.96,1.98,2.02], # pt 2
                # [1.72,1.76,1.78,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.96,1.98,2.02], # pt 3
                # [1.72,1.76,1.78,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.96,1.98,2.02], # pt 4
                # [1.72,1.76,1.78,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.96,1.98,2.02], # pt 5
                # [1.72,1.76,1.78,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.96,1.98,2.02], # pt 6
                # [1.72,1.76,1.78,1.80,1.82,1.84,1.86,1.87,1.88,1.90,1.92,1.94,1.96,1.98,2.02], # pt 7
                # [1.72,1.76,1.78,1.80,1.82,1.84,1.86,1.88,1.90,1.92,1.94,1.96,1.98,2.00,2.04], # pt 8
                # [1.72,1.76,1.78,1.80,1.82,1.84,1.86,1.88,1.90,1.92,1.94,1.96,1.98,2.00,2.04], # pt 9
                # [1.70,1.74,1.76,1.78,1.80,1.82,1.84,1.86,1.88,1.90,1.92,1.94,1.96,1.98,2.04], # pt 10
                # [1.70,1.74,1.76,1.78,1.80,1.82,1.84,1.86,1.88,1.90,1.92,1.94,1.96,1.98,2.04], # pt 11
                # [1.68,1.72,1.76,1.78,1.80,1.82,1.84,1.86,1.88,1.90,1.92,1.94,1.96,1.98,2.02,2.06], # pt 12
                # [1.68,1.72,1.76,1.78,1.80,1.82,1.84,1.86,1.88,1.90,1.92,1.94,1.96,1.98,2.02,2.06], # pt 13
                # [1.68,1.72,1.76,1.78,1.80,1.82,1.84,1.86,1.88,1.90,1.92,1.94,1.96,1.98,2.02,2.06], # pt 14
                # [1.66,1.70,1.74,1.78,1.80,1.82,1.84,1.86,1.88,1.90,1.92,1.94,1.96,2.0,2.04,2.08] # pt 15
                ]
RebinDeltaEta: 1 # 1 no rebin, N (N > 1) rebin by N
RebinDeltaPhi: 1 # 1 no rebin, N (N > 1) rebin by N

# Options for the analysis
doSecPartContamination: false
doRebinSecPart: false
debug: 2 # 0 only final results, 1 keep correlation histos, 2 keep all histos

fitConfig:
    minimizer: 'flarefly'
    Sigma: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02]
    MassFitRanges: [
            [1.72, 2.02],
            [1.72, 2.02],
            [1.72, 2.02],
            [1.72, 2.02],
            [1.72, 2.02],
            [1.72, 2.02],
            [1.72, 2.02],
            [1.72, 2.02],
            [1.72, 2.02],
            [1.72, 2.02],
            [1.72, 2.02],
            [1.72, 2.02],
            [1.72, 2.02],
           ]
    BkgFunc: 'kExpo' # background function. If a single value is provided, it will be used for all pt bins.
    SgnFunc: 'kGaus' # signal function. If a single value is provided, it will be used for all pt bins.
    BkgFuncVn: 'kLin' # background function for vn. If a single value is provided, it will be used for all pt bins.
    
    #_________________________________________________________________________________________________________________________
    # Optional fit configurations, if not set, the default values will be used. If single value is provided, it will be used for all pt bins.
    #FixMean: 0 # 0: do not fix mean, 1: fix mean, default: 0
    #MeanFile: '' # default: ''
    #BoundMean: 0 # 0: Do not set limits on mean range, 1: the mean is set to be between MassMin[i] and MassMax[i]
    #FixSigma: 0 # default: 0
    #FixSigmaFromFile: '' # default: ''
    #SigmaFile: '' # default: ''
    #SigmaMultFactor: 1. # default: 1
    #FixSigmaRatio: 0 # default: 0
    #SigmaRatioFile: "" # default: ""
    #NSigma4SB: 3 # optional
    Rebin: [ 4,    4,    4,    4,    4,    4,    4,    8,    8,    10,    10,    10,    10,    8,    8] # optional, default: 1
    #InclSecPeak: 0 # 0: do not include secondary peak, 1: include secondary peak, default: 0
    #SigmaSecPeak: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02] # optional, default: []. If InclSecPeak = 1, then SigmaSecPeak must be provided.
    #SigmaFileSecPeak: '' # optional, default: ''
    #SigmaMultFactorSecPeak: 1. # optional, default: 1
    #FixSigmaToFirstPeak: 0 # 0: do not fix sigma to the first peak, 1: fix sigma to the first peak, default: 0
    enableRef: false #reflection for D0. 
    ReflFunc: "2gaus" # reflection function, default: "2gaus". D0 specific, not available for others
    # reflFile: ''
    # if `enableRef` is set to `true`,  and `ReflFile` is empty, then `ReflFile` will be aotumatically filled.
    # if `ReflFile` is filled, then it will use the filled one
    #__________________________________________________________________________________________________________________________